name: First Workflow

on: 
    workflow_dispatch:
    push:


jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "Welcome to the first workflow!"

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md