name: Matrix Strategy Workflow

on: 
    workflow_dispatch:
    push:

jobs:
    matrix:
        name: Matrix Job
        strategy: 
            matrix:
                os: [ubuntu-latest, ubuntu-22.04, windows-latest, macos-latest]
                cmd: [Matrix Strategy 1, Matrix Strategy 2]
                exclude:
                    - os: [windows-latest, macos-latest]
                      cmd: Matrix Strategy 2
                include:
                    - os: ubuntu-latest
                      cmd: Matrix Strategy 3
        runs-on: ${{ matrix.os }} 
        steps:
            - name: Script execution on ${{ matrix.os }} 
              run: |
                echo "${{ matrix.cmd }}" >> matrix.txt
                cat matrix.txt