name: Third Workflow

on: 
    workflow_dispatch:
    push:

env:
    VARIABLE1: ${{ vars.VARIABLE1 }}
    SECRET1: ${{ secrets.SECRET1 }}

jobs:
    first_job:
        name: Checkout and execute script
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Script execution
              run: |
                ls -la
                chmod +x ascii.sh
                ls -la
                cat $SECRET1
                cat $VARIABLE1
                ./ascii.sh
        
            - name: Artifact upload
              uses: actions/upload-artifact@v4
              with:
                name: dragon_artifact
                path: dragon.txt


    second_job:
        name: Cat dragon.txt
        needs: first_job
        runs-on: ubuntu-latest
        steps:
            - name: Artifact download
              uses: actions/download-artifact@v4
              with:
                name: dragon_artifact
                path: dragon.txt

            - name: Script execution
              run: |
                ls -la
