name: Third Workflow

on: 
    workflow_dispatch:
    push:


jobs:
    first_job:
        name: Checkout and execute script
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Script execution
              run: |
                ls -la
                chmod +x ascii.sh
                ls -la
                ./ascii.sh

    second_job:
        name: List and wait
        runs-on: ubuntu-latest
        needs: first_job
        steps:
            - name: Script execution
              run: |
                ls -la
                sleep 5