name: Third Workflow

on: 
    workflow_dispatch:
    push:


jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Script execution
              run: |
                chmod +x ./ascii.sh
                ./ascii.sh